language: node_js
before_install:
  - curl -L -O https://github.com/validator/validator/releases/download/16.1.1/vnu.jar_16.1.1.zip
  - unzip -o -d vnu vnu.jar_16.1.1.zip
jdk:
  - oraclejdk8
before_script: pwd && ls && java -version && export NU_VALIDATOR_JAR=$PWD/vnu/vnu.jar
script: npm run cover
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "stable"
after_success:
  - npm run coveralls
