language: node_js
sudo: false
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - curl -L -O https://github.com/validator/validator/releases/download/15.6.29/vnu.jar_15.6.29.zip
  - unzip -o -d vnu vnu.jar_15.6.29.zip
  - java -version
  - export NU_VALIDATOR_JAR=$PWD/vnu/dist/vnu.jar
script: npm run cover
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "stable"
after_success:
  - npm run coveralls
