language: node_js
before_install: curl -L -O https://github.com/validator/validator/releases/download/16.1.1/vnu.jar_16.1.1.zip && unzip vnu.jar_16.1.1.zip && unzip -o vnu.jar_16.1.1.zip
install: sudo add-apt-repository ppa:webupd8team/java && sudo apt-get update && sudo apt-get install oracle-java8-installer -y
before_script: pwd && ls && java -version && export NU_VALIDATOR_JAR=$PWD/dist/vnu.jar
script: npm run cover
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "stable"
after_success:
  - npm run coveralls
