.TH "LINKDOWN" "1" "February 2016" "linkdown 1.0.7" "User Commands"
.SH "NAME"
linkdown
.SH "USAGE"

.SP
linkdown <command> [\-h] [\-\-color|\-\-no\-color] [\-\-bail] [\-h|\-\-help]
.br
         [\-\-version] [\-c|\-\-conf==<file...>] [\-\-log\-level==<level>]
.br
         [\-\-depth==<int>] <args>
.SH "DESCRIPTION"
.PP
Link manipulation tool.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBinfo, i\fR: Print crawl information.
.IP "\[ci]" 4
\fBvalidate, v\fR: Validate (X)HTML pages (nu validator).
.IP "\[ci]" 4
\fBhelp\fR: Show help for commands.
.EL
.SH "OPTIONS"
.BL
.IP "\[ci]" 4
\fB\-c, \-\-conf==[file...]\fR: Load crawler configuration files.
.IP "\[ci]" 4
\fB\-h, \-\-help\fR: Display this help and exit.
.IP "\[ci]" 4
\fB\-\-[no]\-color\fR: Enable or disable terminal colors.
.IP "\[ci]" 4
\fB\-\-bail\fR: Exit on first non\-2xx response code.
.IP "\[ci]" 4
\fB\-\-log\-level==[level]\fR: Set the log level.
.IP "\[ci]" 4
\fB\-\-depth==[int]\fR: Maximum depth to recurse.
.IP "\[ci]" 4
\fB\-\-version\fR: Print version and exit.
.EL
.SH "REDIRECTS"
.PP
Redirects are automatically followed provided the redirect is to the same host.
.SH "EXAMPLE"
.PP
Print crawl information:

  linkdown info http://example.com
.SH "BUGS"
.PP
Report bugs to https://github.com/tmpfs/linkdown/issues.
