.TH "LINKDOWN-VALIDATE" "1" "February 2016" "linkdown-validate 1.0.3" "User Commands"
.SH "NAME"
linkdown-validate
.SH "USAGE"

.SP
linkdown validate [\-\-jar==<file>] <args>
.br
linkdown v [\-\-jar==<file>] <args>
.SH "DESCRIPTION"
.PP
Validate HTML pages with the nu validator.
.SH "OPTIONS"
.BL
.IP "\[ci]" 4
\fB\-\-jar==[file]\fR: Path to the validator jar file.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/tmpfs/linkdown/issues.
