.TH "LINKDOWN" "1" "February 2016" "linkdown 1.0.3" "User Commands"
.SH "NAME"
linkdown
.SH "USAGE"

.SP
linkdown <command> [\-h] [\-\-color|\-\-no\-color] [\-\-follow]
.br
         [\-h|\-\-help] [\-\-version] [\-c|\-\-conf==<file...>]
.br
         [\-\-log\-level==<level>] [\-\-depth==<int>] <args>
.SH "DESCRIPTION"
.PP
Link manipulation tool.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBinfo, i\fR: Print link information.
.IP "\[ci]" 4
\fBvalidate, v\fR: Validate HTML pages with the nu validator.
.IP "\[ci]" 4
\fBhelp\fR: Show help for commands.
.EL
.SH "OPTIONS"
.BL
.IP "\[ci]" 4
\fB\-c, \-\-conf==[file...]\fR: Load crawler configuration files.
.IP "\[ci]" 4
\fB\-h, \-\-help\fR: Display this help and exit.
.IP "\[ci]" 4
\fB\-\-[no]\-color\fR: Enable or disable terminal colors.
.IP "\[ci]" 4
\fB\-\-log\-level==[level]\fR: Set the log level.
.IP "\[ci]" 4
\fB\-\-depth==[int]\fR: Maximum depth to recurse.
.IP "\[ci]" 4
\fB\-\-follow\fR: Follow redirects.
.IP "\[ci]" 4
\fB\-\-version\fR: Print version and exit.
.EL
.SH "EXAMPLE"
.PP
Print links:

  linkdown info http://example.com
.SH "BUGS"
.PP
Report bugs to https://github.com/tmpfs/linkdown/issues.
.SH "SEE ALSO"
.PP
${see_also}
