.TH "LINKDOWN-LIST" "1" "February 2016" "linkdown-list 1.0.10" "User Commands"
.SH "NAME"
linkdown-list -- Print discovered links.
.SH "USAGE"

.SP
linkdown list <args>
.br
linkdown ls <args>
.SH "DESCRIPTION"
.PP
If the \fB\-\-json\fR option is given the links are printed to stdout as line\-delimited JSON documents with the fields \fBurl\fR and \fBresources\fR.
.SH "BUGS"
.PP
Report bugs to https://github.com/tmpfs/linkdown/issues.
