.TH "LINKDOWN-VALIDATE" "1" "February 2016" "linkdown-validate 1.0.7" "User Commands"
.SH "NAME"
linkdown-validate
.SH "USAGE"

.SP
linkdown validate [\-\-errors\-only] [\-\-format==<fmt>]
.br
         [\-\-jar==<file>] <args>
.br
linkdown v [\-\-errors\-only] [\-\-format==<fmt>] [\-\-jar==<file>]
.br
         <args>
.SH "DESCRIPTION"
.PP
Validate (X)HTML pages (nu validator).
.SH "OPTIONS"
.BL
.IP "\[ci]" 4
\fB\-\-format==[fmt]\fR: Validator output format.
.IP "\[ci]" 4
\fB\-\-jar==[file]\fR: Path to the validator jar file.
.IP "\[ci]" 4
\fB\-\-errors\-only\fR: Warnings and info messages are not reported.
.EL
.PP
This command will fetch all pages ending with the \fB.htm\fR, \fB.html\fR, \fB.xhtml\fR and \fB.xht\fR extensions; URLs with no file extension are assumed to be directories serving (X)HTML pages. Each downloaded file is written to a temporary file and passed to the validator.
.PP
To use this command you must have java(1) installed (version 8 is recommended) and specify the path to the nu validator jar by setting \fB\-\-jar\fR or the environment variable \fBNU_VALIDATOR_JAR\fR. 
.PP
If the server responds with a MIME type other than \fBtext/html\fR or \fBapplication/xhtml+xml\fR validation is skipped and a warning is printed.
.PP
Without the \fB\-\-format\fR option the format is set to \fBjson\fR; the response document is parsed and printed to stderr.
.PP
When the \fB\-\-format\fR option is given the raw validator output is printed to stdout, the first line is the remote URL, followed by the validator output followed by a newline.
.PP
Because all log messages are sent to stderr this means you can get an easy to parse log file with all validation results using \fBlinkdown v \-\-format json http://example.com > validation.log\fR.
.SH "BUGS"
.PP
Report bugs to https://github.com/tmpfs/linkdown/issues.
